// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDjtnwkU7uQ3Fz8zmp9Gp6RJ8nzS7W-P0',
    appId: '1:112575732584:web:8c1b5df5f456d022a0d4dd',
    messagingSenderId: '112575732584',
    projectId: 'nossos-pontos',
    authDomain: 'nossos-pontos.firebaseapp.com',
    storageBucket: 'nossos-pontos.appspot.com',
    measurementId: 'G-9GZVX7Q79G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNDOzAn058KlD6k31JCJhXb6uKLqjjBr0',
    appId: '1:112575732584:android:7b8403a9be33a46ea0d4dd',
    messagingSenderId: '112575732584',
    projectId: 'nossos-pontos',
    storageBucket: 'nossos-pontos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm6oUyxVuFk2sAQRpTNqY82W8y_FlbKb0',
    appId: '1:112575732584:ios:9e951fc23ae3a055a0d4dd',
    messagingSenderId: '112575732584',
    projectId: 'nossos-pontos',
    storageBucket: 'nossos-pontos.appspot.com',
    iosBundleId: 'com.example.nossosPontos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm6oUyxVuFk2sAQRpTNqY82W8y_FlbKb0',
    appId: '1:112575732584:ios:9e951fc23ae3a055a0d4dd',
    messagingSenderId: '112575732584',
    projectId: 'nossos-pontos',
    storageBucket: 'nossos-pontos.appspot.com',
    iosBundleId: 'com.example.nossosPontos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDjtnwkU7uQ3Fz8zmp9Gp6RJ8nzS7W-P0',
    appId: '1:112575732584:web:90d02a883ac96792a0d4dd',
    messagingSenderId: '112575732584',
    projectId: 'nossos-pontos',
    authDomain: 'nossos-pontos.firebaseapp.com',
    storageBucket: 'nossos-pontos.appspot.com',
    measurementId: 'G-5JB1YRQN1X',
  );
}
